SELECT
c.NAME,
o.PRICE
FROM CUSTOMERS AS c
JOIN ORDERS AS o
ON c.ORDER_ID = o.ID
WHERE
o.ORDER_DATE BETWEEN (
SELECT MIN(ORDER_DATE) FROM ORDERS
) AND (
SELECT MIN(ORDER_DATE) + INTERVAL '10 year' FROM ORDERS
)
ORDER BY o.PRICE DESC
LIMIT 1